-- 表数据: questions
-- 导出时间: 2025-08-25 20:20:11
-- 记录数: 168

DELETE FROM questions;

INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (1, 1, 'mcq', '[选择题] 第1套 第1题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 1, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (2, 1, 'mcq', '[选择题] 第1套 第2题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 2, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (3, 1, 'mcq', '[选择题] 第1套 第3题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 3, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (4, 1, 'mcq', '[选择题] 第1套 第4题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 4, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (5, 1, 'mcq', '[选择题] 第1套 第5题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 5, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (6, 1, 'mcq', '[选择题] 第1套 第6题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 6, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (7, 1, 'mcq', '[选择题] 第1套 第7题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 7, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (8, 1, 'mcq', '[选择题] 第1套 第8题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 8, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (9, 1, 'mcq', '[选择题] 第1套 第9题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 9, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (10, 1, 'mcq', '[选择题] 第1套 第10题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 10, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (11, 1, 'mcq', '[选择题] 第1套 第11题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 11, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (12, 1, 'mcq', '[选择题] 第1套 第12题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 12, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (13, 1, 'tf', '[判断题] 第1套 第1题：/root为普通用户家目录。', NULL, 'False', 2, 13, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (14, 1, 'tf', '[判断题] 第1套 第2题：/root为普通用户家目录。', NULL, 'False', 2, 14, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (15, 1, 'tf', '[判断题] 第1套 第3题：/root为普通用户家目录。', NULL, 'False', 2, 15, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (16, 1, 'tf', '[判断题] 第1套 第4题：/root为普通用户家目录。', NULL, 'False', 2, 16, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (17, 1, 'tf', '[判断题] 第1套 第5题：/root为普通用户家目录。', NULL, 'False', 2, 17, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (18, 1, 'tf', '[判断题] 第1套 第6题：/root为普通用户家目录。', NULL, 'False', 2, 18, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (19, 1, 'tf', '[判断题] 第1套 第7题：/root为普通用户家目录。', NULL, 'False', 2, 19, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (20, 1, 'tf', '[判断题] 第1套 第8题：/root为普通用户家目录。', NULL, 'False', 2, 20, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (21, 1, 'fill', '[填空题] 第1套 第1题：查看当前路径的命令是____。', NULL, 'pwd', 2, 21, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (22, 1, 'fill', '[填空题] 第1套 第2题：查看当前路径的命令是____。', NULL, 'pwd', 2, 22, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (23, 1, 'fill', '[填空题] 第1套 第3题：查看当前路径的命令是____。', NULL, 'pwd', 2, 23, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (24, 1, 'fill', '[填空题] 第1套 第4题：查看当前路径的命令是____。', NULL, 'pwd', 2, 24, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (25, 1, 'fill', '[填空题] 第1套 第5题：查看当前路径的命令是____。', NULL, 'pwd', 2, 25, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (26, 1, 'fill', '[填空题] 第1套 第6题：查看当前路径的命令是____。', NULL, 'pwd', 2, 26, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (27, 1, 'short', '[简答题] 第1套 第1题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 27, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (28, 1, 'short', '[简答题] 第1套 第2题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 28, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (29, 1, 'short', '[简答题] 第1套 第3题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 29, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (30, 1, 'short', '[简答题] 第1套 第4题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 30, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (31, 2, 'mcq', '[选择题] 第2套 第1题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 1, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (32, 2, 'mcq', '[选择题] 第2套 第2题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 2, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (33, 2, 'mcq', '[选择题] 第2套 第3题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 3, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (34, 2, 'mcq', '[选择题] 第2套 第4题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 4, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (35, 2, 'mcq', '[选择题] 第2套 第5题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 5, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (36, 2, 'mcq', '[选择题] 第2套 第6题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 6, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (37, 2, 'mcq', '[选择题] 第2套 第7题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 7, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (38, 2, 'mcq', '[选择题] 第2套 第8题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 8, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (39, 2, 'mcq', '[选择题] 第2套 第9题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 9, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (40, 2, 'mcq', '[选择题] 第2套 第10题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 10, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (41, 2, 'mcq', '[选择题] 第2套 第11题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 11, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (42, 2, 'mcq', '[选择题] 第2套 第12题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 12, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (43, 2, 'tf', '[判断题] 第2套 第1题：/root为普通用户家目录。', NULL, 'False', 2, 13, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (44, 2, 'tf', '[判断题] 第2套 第2题：/root为普通用户家目录。', NULL, 'False', 2, 14, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (45, 2, 'tf', '[判断题] 第2套 第3题：/root为普通用户家目录。', NULL, 'False', 2, 15, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (46, 2, 'tf', '[判断题] 第2套 第4题：/root为普通用户家目录。', NULL, 'False', 2, 16, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (47, 2, 'tf', '[判断题] 第2套 第5题：/root为普通用户家目录。', NULL, 'False', 2, 17, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (48, 2, 'tf', '[判断题] 第2套 第6题：/root为普通用户家目录。', NULL, 'False', 2, 18, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (49, 2, 'tf', '[判断题] 第2套 第7题：/root为普通用户家目录。', NULL, 'False', 2, 19, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (50, 2, 'tf', '[判断题] 第2套 第8题：/root为普通用户家目录。', NULL, 'False', 2, 20, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (51, 2, 'fill', '[填空题] 第2套 第1题：查看当前路径的命令是____。', NULL, 'pwd', 2, 21, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (52, 2, 'fill', '[填空题] 第2套 第2题：查看当前路径的命令是____。', NULL, 'pwd', 2, 22, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (53, 2, 'fill', '[填空题] 第2套 第3题：查看当前路径的命令是____。', NULL, 'pwd', 2, 23, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (54, 2, 'fill', '[填空题] 第2套 第4题：查看当前路径的命令是____。', NULL, 'pwd', 2, 24, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (55, 2, 'fill', '[填空题] 第2套 第5题：查看当前路径的命令是____。', NULL, 'pwd', 2, 25, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (56, 2, 'fill', '[填空题] 第2套 第6题：查看当前路径的命令是____。', NULL, 'pwd', 2, 26, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (57, 2, 'short', '[简答题] 第2套 第1题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 27, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (58, 2, 'short', '[简答题] 第2套 第2题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 28, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (59, 2, 'short', '[简答题] 第2套 第3题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 29, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (60, 2, 'short', '[简答题] 第2套 第4题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 30, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (61, 3, 'mcq', '[选择题] 第3套 第1题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 1, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (62, 3, 'mcq', '[选择题] 第3套 第2题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 2, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (63, 3, 'mcq', '[选择题] 第3套 第3题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 3, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (64, 3, 'mcq', '[选择题] 第3套 第4题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 4, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (65, 3, 'mcq', '[选择题] 第3套 第5题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 5, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (66, 3, 'mcq', '[选择题] 第3套 第6题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 6, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (67, 3, 'mcq', '[选择题] 第3套 第7题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 7, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (68, 3, 'mcq', '[选择题] 第3套 第8题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 8, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (69, 3, 'mcq', '[选择题] 第3套 第9题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 9, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (70, 3, 'mcq', '[选择题] 第3套 第10题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 10, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (71, 3, 'mcq', '[选择题] 第3套 第11题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 11, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (72, 3, 'mcq', '[选择题] 第3套 第12题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 12, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (73, 3, 'tf', '[判断题] 第3套 第1题：/root为普通用户家目录。', NULL, 'False', 2, 13, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (74, 3, 'tf', '[判断题] 第3套 第2题：/root为普通用户家目录。', NULL, 'False', 2, 14, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (75, 3, 'tf', '[判断题] 第3套 第3题：/root为普通用户家目录。', NULL, 'False', 2, 15, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (76, 3, 'tf', '[判断题] 第3套 第4题：/root为普通用户家目录。', NULL, 'False', 2, 16, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (77, 3, 'tf', '[判断题] 第3套 第5题：/root为普通用户家目录。', NULL, 'False', 2, 17, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (78, 3, 'tf', '[判断题] 第3套 第6题：/root为普通用户家目录。', NULL, 'False', 2, 18, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (79, 3, 'tf', '[判断题] 第3套 第7题：/root为普通用户家目录。', NULL, 'False', 2, 19, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (80, 3, 'tf', '[判断题] 第3套 第8题：/root为普通用户家目录。', NULL, 'False', 2, 20, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (81, 3, 'fill', '[填空题] 第3套 第1题：查看当前路径的命令是____。', NULL, 'pwd', 2, 21, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (82, 3, 'fill', '[填空题] 第3套 第2题：查看当前路径的命令是____。', NULL, 'pwd', 2, 22, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (83, 3, 'fill', '[填空题] 第3套 第3题：查看当前路径的命令是____。', NULL, 'pwd', 2, 23, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (84, 3, 'fill', '[填空题] 第3套 第4题：查看当前路径的命令是____。', NULL, 'pwd', 2, 24, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (85, 3, 'fill', '[填空题] 第3套 第5题：查看当前路径的命令是____。', NULL, 'pwd', 2, 25, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (86, 3, 'fill', '[填空题] 第3套 第6题：查看当前路径的命令是____。', NULL, 'pwd', 2, 26, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (87, 3, 'short', '[简答题] 第3套 第1题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 27, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (88, 3, 'short', '[简答题] 第3套 第2题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 28, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (89, 3, 'short', '[简答题] 第3套 第3题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 29, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (90, 3, 'short', '[简答题] 第3套 第4题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 30, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (91, 4, 'mcq', '[选择题] 第4套 第1题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 1, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (92, 4, 'mcq', '[选择题] 第4套 第2题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 2, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (93, 4, 'mcq', '[选择题] 第4套 第3题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 3, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (94, 4, 'mcq', '[选择题] 第4套 第4题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 4, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (95, 4, 'mcq', '[选择题] 第4套 第5题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 5, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (96, 4, 'mcq', '[选择题] 第4套 第6题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 6, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (97, 4, 'mcq', '[选择题] 第4套 第7题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 7, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (98, 4, 'mcq', '[选择题] 第4套 第8题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 8, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (99, 4, 'mcq', '[选择题] 第4套 第9题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 9, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (100, 4, 'mcq', '[选择题] 第4套 第10题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 10, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (101, 4, 'mcq', '[选择题] 第4套 第11题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 11, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (102, 4, 'mcq', '[选择题] 第4套 第12题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 12, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (103, 4, 'tf', '[判断题] 第4套 第1题：/root为普通用户家目录。', NULL, 'False', 2, 13, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (104, 4, 'tf', '[判断题] 第4套 第2题：/root为普通用户家目录。', NULL, 'False', 2, 14, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (105, 4, 'tf', '[判断题] 第4套 第3题：/root为普通用户家目录。', NULL, 'False', 2, 15, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (106, 4, 'tf', '[判断题] 第4套 第4题：/root为普通用户家目录。', NULL, 'False', 2, 16, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (107, 4, 'tf', '[判断题] 第4套 第5题：/root为普通用户家目录。', NULL, 'False', 2, 17, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (108, 4, 'tf', '[判断题] 第4套 第6题：/root为普通用户家目录。', NULL, 'False', 2, 18, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (109, 4, 'tf', '[判断题] 第4套 第7题：/root为普通用户家目录。', NULL, 'False', 2, 19, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (110, 4, 'tf', '[判断题] 第4套 第8题：/root为普通用户家目录。', NULL, 'False', 2, 20, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (111, 4, 'fill', '[填空题] 第4套 第1题：查看当前路径的命令是____。', NULL, 'pwd', 2, 21, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (112, 4, 'fill', '[填空题] 第4套 第2题：查看当前路径的命令是____。', NULL, 'pwd', 2, 22, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (113, 4, 'fill', '[填空题] 第4套 第3题：查看当前路径的命令是____。', NULL, 'pwd', 2, 23, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (114, 4, 'fill', '[填空题] 第4套 第4题：查看当前路径的命令是____。', NULL, 'pwd', 2, 24, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (115, 4, 'fill', '[填空题] 第4套 第5题：查看当前路径的命令是____。', NULL, 'pwd', 2, 25, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (116, 4, 'fill', '[填空题] 第4套 第6题：查看当前路径的命令是____。', NULL, 'pwd', 2, 26, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (117, 4, 'short', '[简答题] 第4套 第1题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 27, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (118, 4, 'short', '[简答题] 第4套 第2题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 28, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (119, 4, 'short', '[简答题] 第4套 第3题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 29, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (120, 4, 'short', '[简答题] 第4套 第4题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 30, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (121, 5, 'mcq', '[选择题] 第5套 第1题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 1, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (122, 5, 'mcq', '[选择题] 第5套 第2题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 2, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (123, 5, 'mcq', '[选择题] 第5套 第3题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 3, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (124, 5, 'mcq', '[选择题] 第5套 第4题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 4, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (125, 5, 'mcq', '[选择题] 第5套 第5题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 5, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (126, 5, 'mcq', '[选择题] 第5套 第6题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 6, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (127, 5, 'mcq', '[选择题] 第5套 第7题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 7, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (128, 5, 'mcq', '[选择题] 第5套 第8题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 8, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (129, 5, 'mcq', '[选择题] 第5套 第9题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 9, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (130, 5, 'mcq', '[选择题] 第5套 第10题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 10, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (131, 5, 'mcq', '[选择题] 第5套 第11题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 11, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (132, 5, 'mcq', '[选择题] 第5套 第12题：Linux命令ls的作用是？', '["列出目录内容", "删除文件", "显示文件内容", "切换目录"]', 'A', 2, 12, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (133, 5, 'tf', '[判断题] 第5套 第1题：/root为普通用户家目录。', NULL, 'False', 2, 13, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (134, 5, 'tf', '[判断题] 第5套 第2题：/root为普通用户家目录。', NULL, 'False', 2, 14, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (135, 5, 'tf', '[判断题] 第5套 第3题：/root为普通用户家目录。', NULL, 'False', 2, 15, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (136, 5, 'tf', '[判断题] 第5套 第4题：/root为普通用户家目录。', NULL, 'False', 2, 16, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (137, 5, 'tf', '[判断题] 第5套 第5题：/root为普通用户家目录。', NULL, 'False', 2, 17, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (138, 5, 'tf', '[判断题] 第5套 第6题：/root为普通用户家目录。', NULL, 'False', 2, 18, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (139, 5, 'tf', '[判断题] 第5套 第7题：/root为普通用户家目录。', NULL, 'False', 2, 19, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (140, 5, 'tf', '[判断题] 第5套 第8题：/root为普通用户家目录。', NULL, 'False', 2, 20, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (141, 5, 'fill', '[填空题] 第5套 第1题：查看当前路径的命令是____。', NULL, 'pwd', 2, 21, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (142, 5, 'fill', '[填空题] 第5套 第2题：查看当前路径的命令是____。', NULL, 'pwd', 2, 22, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (143, 5, 'fill', '[填空题] 第5套 第3题：查看当前路径的命令是____。', NULL, 'pwd', 2, 23, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (144, 5, 'fill', '[填空题] 第5套 第4题：查看当前路径的命令是____。', NULL, 'pwd', 2, 24, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (145, 5, 'fill', '[填空题] 第5套 第5题：查看当前路径的命令是____。', NULL, 'pwd', 2, 25, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (146, 5, 'fill', '[填空题] 第5套 第6题：查看当前路径的命令是____。', NULL, 'pwd', 2, 26, '1:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (147, 5, 'short', '[简答题] 第5套 第1题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 27, '2:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (148, 5, 'short', '[简答题] 第5套 第2题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 28, '3:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (149, 5, 'short', '[简答题] 第5套 第3题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 29, '4:4');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (150, 5, 'short', '[简答题] 第5套 第4题：简述使用Docker部署Hadoop伪分布式的大致步骤。', NULL, '{"keywords": ["拉取镜像", "配置core-site", "启动容器", "HDFS格式化", "NameNode/DataNode"]}', 4, 30, '5:5');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (151, 6, 'mcq', 'HDFS中NameNode的主要作用是什么？', '["存储文件数据块", "管理文件系统命名空间和元数据", "执行MapReduce任务", "监控集群状态"]', 'B', 2, 1, '5:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (152, 6, 'mcq', 'HDFS默认的数据块大小是多少？', '["64MB", "128MB", "256MB", "512MB"]', 'B', 2, 2, '5:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (153, 6, 'tf', 'HDFS支持随机写入操作。', NULL, 'False', 2, 3, '5:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (154, 6, 'tf', 'DataNode负责存储实际的文件数据块。', NULL, 'True', 2, 4, '5:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (155, 6, 'fill', 'HDFS中负责管理文件系统命名空间的组件是____。', NULL, 'NameNode', 2, 5, '5:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (156, 6, 'short', '简述HDFS的读写流程。', NULL, '{"keywords": ["客户端请求", "NameNode返回DataNode列表", "直接与DataNode通信", "数据块复制", "确认写入"]}', 4, 6, '5:1');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (157, 6, 'mcq', 'YARN中ResourceManager的主要职责是什么？', '["执行具体任务", "管理集群资源分配", "存储数据", "监控网络状态"]', 'B', 2, 7, '5:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (158, 6, 'mcq', 'ApplicationMaster的作用是什么？', '["管理整个集群", "协调单个应用程序的执行", "存储应用数据", "监控硬件状态"]', 'B', 2, 8, '5:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (159, 6, 'tf', 'NodeManager运行在集群的每个工作节点上。', NULL, 'True', 2, 9, '5:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (160, 6, 'tf', 'YARN只能运行MapReduce应用程序。', NULL, 'False', 2, 10, '5:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (161, 6, 'fill', 'YARN中负责单个应用程序资源协调的组件是____。', NULL, 'ApplicationMaster', 2, 11, '5:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (162, 6, 'short', '描述YARN的资源调度流程。', NULL, '{"keywords": ["客户端提交应用", "ResourceManager分配ApplicationMaster", "ApplicationMaster请求资源", "NodeManager启动Container", "任务执行"]}', 4, 12, '5:2');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (163, 6, 'mcq', 'MapReduce中Map阶段的主要作用是什么？', '["汇总结果", "处理和转换输入数据", "存储数据", "监控任务"]', 'B', 2, 13, '5:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (164, 6, 'mcq', 'Shuffle阶段发生在哪两个阶段之间？', '["输入和Map", "Map和Reduce", "Reduce和输出", "输入和输出"]', 'B', 2, 14, '5:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (165, 6, 'tf', 'MapReduce程序必须同时包含Map和Reduce阶段。', NULL, 'False', 2, 15, '5:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (166, 6, 'tf', 'Combiner可以减少网络传输的数据量。', NULL, 'True', 2, 16, '5:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (167, 6, 'fill', 'MapReduce中负责汇总Map输出结果的阶段是____。', NULL, 'Reduce', 2, 17, '5:3');
INSERT INTO questions (id, exam_id, qtype, prompt, options, answer, score, ord, knowledge_ref) VALUES (168, 6, 'short', '解释MapReduce的工作原理和优势。', NULL, '{"keywords": ["分而治之", "并行处理", "容错性", "Map映射", "Reduce归约", "可扩展性"]}', 4, 18, '5:3');

